#!groovy

// Generated by IBM TransformationAdvisor
// Mon Feb 11 13:17:13 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}