#!groovy

// Generated by IBM TransformationAdvisor
// Thu Feb 07 15:19:18 GMT 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}