#!groovy

// Generated by IBM TransformationAdvisor
// Wed Feb 06 14:43:29 GMT 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}